OriginProtocol/arm-oeth

foundry.toml
test/Base.sol
test/fork/LidoFixedPriceMultiLpARM/Constructor.t.sol
test/fork/LidoFixedPriceMultiLpARM/Deposit.t.sol
test/fork/LidoFixedPriceMultiLpARM/RequestRedeem.t.sol
test/fork/LidoFixedPriceMultiLpARM/SwapExactTokensForTokens.t.sol
test/fork/LidoFixedPriceMultiLpARM/SwapTokensForExactTokens.t.sol
test/fork/shared/Shared.sol
test/fork/utils/Helpers.sol
test/fork/utils/Modifiers.sol

Add concrete and fuzz test for two external functions in `LidoFixedPriceMultiLpARM.sol`:
- `swapExactTokensForTokens()`
- `swapTokensForExactTokens()`
For fuzzing:
- Put a random price for one token.
- Put random liquidity for the other in the ARM.
- Swap a random amount.
Coverage 100% for these 2 functions.

Add test for Swaps in LidoFixedPriceMultiLpARM.sol.

---

src/contracts/AbstractARM.sol
test/fork/LidoFixedPriceMultiLpARM/ClaimRedeem.t.sol
test/fork/LidoFixedPriceMultiLpARM/Constructor.t.sol
test/fork/LidoFixedPriceMultiLpARM/Deposit.t.sol
test/fork/LidoFixedPriceMultiLpARM/RequestRedeem.t.sol

This is a big refactor from how the performance fees were previously calculated. Instead of the performance fee accrued when liquidity was deposited or redeemed, the performance fee is calculated when the fee is collected.
This change can be done as `totalAssets` already adjusted for the performance fee. This means deposit and redeem could used the existing `totalAssets` and not do and fee accrual. This means the `feesAccrued` storage variable is no longer needed.
It does mean `lastAvailableAssets` needs to be adjusted on each deposit and redeem. It also means `lastAvailableAssets` can be negative. The simple scenario for this is:
- single liquidity provider deposits
- swaps earn a profit more than the initial mint when the contract is initialized
- the lp redeems all their shares
- …

Only accrued fees when they are collected

---

script/deploy/mainnet/003_UpgradeLidoARMScript.sol
src/contracts/Interfaces.sol
src/contracts/ZapperLidoARM.sol
test/Base.sol
test/fork/Zapper/Deposit.t.sol
test/fork/Zapper/RescueToken.sol
test/fork/shared/Shared.sol

Zapper to deposit liquidity in ARM with raw ETH instead of wETH in a single transaction.
At the moment, as only the msg.sender can be the withdrawer, it is not possible for the zapper to withdraw for someone and then unwrap wETH for ETH.

Add Zapper for LidoARM

---

src/contracts/AbstractARM.sol
src/contracts/LidoARM.sol
test/fork/LidoFixedPriceMultiLpARM/Deposit.t.sol
test/fork/LidoFixedPriceMultiLpARM/SetCrossPrice.t.sol
test/fork/LidoFixedPriceMultiLpARM/Setters.t.sol

* Set buy and sell prices in `initialize` function
* `setCrossPrice` now validates buy and sell prices against the new cross price
TODO

Pre launch changes

---

src/contracts/AbstractARM.sol
src/contracts/CapManager.sol
test/fork/LidoFixedPriceMultiLpARM/ClaimRedeem.t.sol
test/fork/LidoFixedPriceMultiLpARM/Deposit.t.sol
test/fork/LidoFixedPriceMultiLpARM/RequestRedeem.t.sol
test/fork/LidoFixedPriceMultiLpARM/Setters.t.sol
test/fork/LidoFixedPriceMultiLpARM/SwapExactTokensForTokens.t.sol
test/fork/LidoFixedPriceMultiLpARM/SwapTokensForExactTokens.t.sol
test/fork/Zapper/Deposit.t.sol
test/fork/utils/Modifiers.sol
test/smoke/LidoARMSmokeTest.t.sol

* Increased rounding in `swapTokensForExactTokens` to cover 1-2 wei lost with stETH transfers
* Added test modifiers `disableCaps`, `setPrices` and `setArmBalances`
* Improved swap fuzz tests

Swap rounding

---

Makefile
foundry.toml

- Remove [etherscan] sections from Makefile as it was making contract verification fail.
- Update forge-std to 1.9.3
- Improve Makefile to exclude invariant test when running `make test`.
- Add `make test-all` to include invariant to test.

Fix contract verification & update Makefile

---

README.md
src/abis/LidoARM.json
src/abis/LidoWithdrawQueue.json
src/js/actions/autoClaimLidoWithdraw.js
src/js/actions/autoRequestLidoWithdraw.js
src/js/actions/collectLidoFees.js
src/js/actions/rollup.config.cjs
src/js/tasks/lido.js
src/js/tasks/lidoQueue.js
src/js/tasks/markets.js
src/js/tasks/tasks.js
src/js/utils/addresses.js
test/fork/LidoFixedPriceMultiLpARM/SetCrossPrice.t.sol
test/invariants/BasicInvariants.sol

* Added new Defender Actions for the Lido ARM
* Added more Hardhat tasks for Lido ARM

Defender Actions

---

.gitignore
README.md
package.json
src/js/actions/rollup.config.cjs
src/js/actions/setPrices.js
src/js/tasks/lido.js
src/js/tasks/lidoPrices.js
src/js/tasks/markets.js
src/js/tasks/tasks.js
src/js/utils/curve.js
test/smoke/LidoARMSmokeTest.t.sol

* Added a setPrices Defender Action that uses Curve pricing

Operational automation

---

src/contracts/utils/Addresses.sol
src/js/actions/autoClaimLidoWithdraw.js
src/js/actions/autoClaimWithdraw.js
src/js/actions/autoRequestLidoWithdraw.js
src/js/actions/autoRequestWithdraw.js
src/js/actions/setPrices.js
src/js/tasks/lido.js
src/js/tasks/lidoPrices.js
src/js/tasks/liquidity.js
src/js/tasks/tasks.js
src/js/utils/addresses.js
src/js/utils/armQueue.js
src/js/utils/block.js
src/js/utils/curve.js
src/js/utils/lido.js
src/js/utils/queue.js
src/js/utils/uniswap.js

* Fix the Hardhat task `snap` task for the OETH ARM
* Added an `offset` to the `setPrices` Hardhat task for the Lido ARM
* Fix `autoClaimWithdraw` Defender Action by adding limit to graphQL call in `claimableRequests`
* Stopped swallowing errors in Defender Actions 
* Added Lido withdrawal queue data to the `snapLido` Hardhat task eg
```
Lido withdrawal queue
19482.915608538620550706 stETH withdrawals
5405.526192315276507261  ETH from deposits
110.613985549906069785   ETH from execution rewards
793.777218526            ETH from validators
6309.917396391182577046  ETH to be finalized
13172.99821214743797366  ETH outstanding
```

Hardhat tasks and Defender Actions

---

test/invariants/handlers/LLMHandler.sol
test/invariants/mocks/MockSTETH.sol

Invariant testing is failing, with this quick fix it should be fixed. 
- Prevent requesting 0 amount withdrawal on Lido.
- Stop stETH from losing one wei on transfer. 
However, I'm currently refactoring the invariant setup, stopping custom-probability distribution, and using a more classical approach. This should improve debugging and try to resolve why user shares are not up only all the time.

Quick fix for failing invariant.

---

src/contracts/LidoARM.sol

* The `requestLidoWithdrawals` and `claimLidoWithdrawals` functions in `LidoARM` have been changed to use `calldata`

N-03 Use calldata instead of memory for external function parameters

---

src/contracts/AbstractARM.sol

* Updated Natspec for `setCrossPrice`

M-01 Potential Denial of Service in setCrossPrice()

---

foundry.toml
src/contracts/LidoARM.sol
test/fork/LidoFixedPriceMultiLpARM/ClaimStETHWithdrawalForWETH.t.sol
test/fork/LidoFixedPriceMultiLpARM/Deposit.t.sol
test/fork/utils/MockCall.sol
test/invariants/BasicInvariants.sol
test/invariants/handlers/LLMHandler.sol

* Moved calculating the Lido claim withdrawal hints off-chain when calling `claimLidoWithdrawals`
Before
```
| Function Name                                                       | min             | avg    | median | max     | # calls |
| claimLidoWithdrawals                                                | 20456           | 36554  | 37265  | 52297   | 10      |
```
After
```
| Function Name                                                       | min             | avg    | median | max     | # calls |
| claimLidoWithdrawals                                                | 15983           | 27233  | 28897  | 39693   | 10      |
```

Gas saving when claiming Lido withdrawals

---

script/deploy/DeployManager.sol
script/deploy/mainnet/005_RegisterLidoWithdrawalsScript.sol
src/contracts/LidoARM.sol
test/smoke/LidoARMSmokeTest.t.sol

The following fixes will be deployed with this upgrade
* https://github.com/OriginProtocol/arm-oeth/pull/52
* https://github.com/OriginProtocol/arm-oeth/pull/53
* https://github.com/OriginProtocol/arm-oeth/pull/58
* https://github.com/OriginProtocol/arm-oeth/pull/50
The update also calls `registerLidoWithdrawalRequests` in the Lido ARM that initializes the new `lidoWithdrawalRequests` mapping of Lido request ids to withdrawal amounts. This can only be executed once by the contract Owner, which is the Timelock.

Upgrade LidoARM and Lido register withdrawal requests

---

Makefile
script/deploy/sonic/001_DeployOriginARM.sol
src/contracts/AbstractARM.sol
src/contracts/LidoARM.sol
src/contracts/OethARM.sol
src/contracts/OriginARM.sol
test/fork/OriginARM/shared/Shared.sol
test/invariants/OriginARM/FuzzerFoundry.sol
test/invariants/OriginARM/Setup.sol
test/unit/shared/Shared.sol

This pull request introduces changes to improve the flexibility and configurability of the `OriginARM` contract by replacing the constant `MIN_SHARES_TO_REDEEM` with an immutable variable `minSharesToRedeem`. It also updates related deployment scripts, test cases, and constructor calls to support this modification. Additionally, there is a minor change in the `Makefile` to adjust the `FOUNDRY_NO_MATCH_CONTRACT` environment variable.
* Replaced the constant `MIN_SHARES_TO_REDEEM` with an immutable variable `minSharesToRedeem` in `AbstractARM` to allow for more dynamic configuration. This includes updates to the constructor and relevant logic where the constant was previously used (`src/contracts/AbstractARM.sol`). [[1]](diffhunk://#diff-41d22a3c9825e8099b1b619e93c45f5bd7b925c76b9d0e66069adf …

Fix: Change MIN_SHARES_TO_REDEEM from constant to immutable.

---

Makefile
foundry.toml
script/deploy/sonic/001_DeployOriginARM.sol
src/contracts/AbstractARM.sol
src/contracts/LidoARM.sol
src/contracts/OethARM.sol
src/contracts/OriginARM.sol
src/contracts/markets/SiloMarket.sol
src/contracts/utils/Addresses.sol
test/fork/Harvester/Collect.sol
test/fork/Harvester/shared/Shared.sol
test/fork/OriginARM/AllocateWithAdapter.sol
test/fork/OriginARM/shared/Shared.sol
test/invariants/OriginARM/FuzzerFoundry.sol
test/invariants/OriginARM/Logger.sol
test/invariants/OriginARM/MathComparisons.sol
test/invariants/OriginARM/Properties.sol
test/invariants/OriginARM/Setup.sol
test/invariants/OriginARM/TargetFunction.sol
test/unit/OriginARM/Allocate.sol
test/unit/shared/Shared.sol

- Plug the SiloMarket.sol contract to `Varlamore` vault, which is an `ERC4626` compliant vault that manage liquidity across multiple Silo markets. 
- Adjust test and deployment script to use this new vault.
- Refactor slightly invariant test setup organization.

Plug `SiloMarket.sol` to Varlamore vault instead of markets.

---

script/deploy/DeployManager.sol
script/deploy/sonic/002_DeployOriginARM.sol

This pull request introduces enhancements to the deployment scripts, focusing on improving the robustness of contract deployment and initialization processes. Key changes include adding a utility function for fetching deployed contract addresses from JSON files, improving argument validation, and refining proxy initialization logic.
* **Utility Function for JSON-Based Address Retrieval**:
- Added `getDeployedAddressInBuild` to fetch contract addresses from deployment JSON files using `stdJson`. This ensures better integration with deployment artifacts.
- Updated the `DeployOriginARMScript` invocation to use `getDeployedAddressInBuild` instead of `getDeployment`.
* **Library and Syntax Enhancements**:
- Imported the `stdJson` library and added a `using stdJson for string` directive for …

Fetch deployed address using build file.

---

Makefile
foundry.toml
test/unit/OriginARM/ClaimRedeem.sol
test/unit/OriginARM/Deposit.sol
test/unit/OriginARM/ManageMarket.sol
test/unit/OriginARM/RequestRedeem.sol
test/unit/OriginARM/TotalAssets.sol

- Add more test to increase Unit coverage (cross-test already ensure 100% coverage).

Increase test Coverage

---

README.md
src/js/actions/allocateLido.js
src/js/actions/rollup.config.cjs
src/js/actions/setPrices.js
src/js/tasks/defender.js
src/js/tasks/lido.js
src/js/tasks/lidoMorphoPrices.js
src/js/tasks/tasks.js
src/js/utils/fluid.js

This pull request updates the `logAssets` function in `src/js/tasks/lido.js` to include balances and percentages for assets held in the active lending market. The changes add support for fetching and displaying the lending market balance and its proportion of total assets, using a hardcoded market address for now.
**Lending Market Integration:**
* Added logic to retrieve the ARM's balance in the active lending market (`Abstract4626MarketWrapper`), calculate its value in assets, and include it in the total asset calculation. The market address is currently hardcoded but will be dynamic in the future.
* Updated output to display the lending market balance and its percentage share alongside other asset categories.
(I generated description using copilot, not bad)

Add lending market data to `snapLido`

---

src/js/actions/setOSSiloPriceAction.js
src/js/tasks/osSiloPrice.js
src/js/tasks/tasks.js

This pull request refactors how contract instances and block tags are passed to the OS Silo price calculation logic. Instead of creating contract instances inside the pricing logic, they are now instantiated earlier and passed as parameters, which improves modularity and testability. Additionally, the code now consistently uses `blockTag` instead of `block` and updates contract calls to use the provided signer and provider.
**Refactoring contract instance management:**
* Contract instances for WS, OS, and Vault tokens are now created outside of the price calculation logic (`setOSSiloPrice` and `estimateAverageWithdrawTime`) and passed in as parameters, rather than being instantiated internally. This change is reflected in both the handler and subtask setup …

Fix Actions for OZ Defender.
